# Generated by Django 6.0.4 on 2026-05-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1997', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/'),
        ),
    ]
