# Generated by Django 6.0.4 on 2026-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1997', '0004_alter_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente_aceptacion', 'Pendiente de Aceptacion'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
